name: Dependabot update Go
on: pull_request

permissions:
  contents: write

jobs:
  golang_update:
    runs-on: ubuntu-latest
    if: github.event.pull_request.user.login == 'dependabot[bot]' && github.repository == 'ivanvc/dispatcher'
    steps:
    - name: Dependabot metadata
      id: metadata
      uses: dependabot/fetch-metadata@21025c705c08248db411dc16f3619e6b5f9ea21a # v2.5.0
      with:
        github-token: "${{ secrets.GITHUB_TOKEN }}"

    - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      if: contains(steps.metadata.outputs.dependency-names, 'golang')
    - name: Set up Go
      if: contains(steps.metadata.outputs.dependency-names, 'golang')
      uses: actions/setup-go@7a3fe6cf4cb3a834922a1244abfce67bcef6a0c5 # v6.2.0
      with:
        go-version-file: 'go.mod'
        cache: true
    - name: Bump Golang version
      if: contains(steps.metadata.outputs.dependency-names, 'golang')
      run: |
        go mod edit -toolchain go${{steps.metadata.outputs.new-version}}
        git config user.name "github-actions[bot]"
        git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git add go.mod
        git commit -m "deps(golang): Bump from ${{steps.metadata.outputs.old-version}} to ${{steps.metadata.outputs.new-version}}"
        git push origin "${GITHUB_REF#refs/heads/}"
